  server:
    port: 8081
  spring:
    kafka:
      bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
        acks: all
        retries: 3
      consumer:
        group-id: mi-life-platform
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      listener:
        ack-mode: record
    application:
      name: mi-life-platform
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:dingping}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:123456}
    redis:
      host: 127.0.0.1
      port: 6379

      lettuce:
        pool:
          max-active: 30
          max-idle: 15
          min-idle: 5
          time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段
  mybatis-plus:
    type-aliases-package: com.study.lifeplatform.entity # 别名扫描包
  logging:
    level:
      com.study.lifeplatform: debug
  ai:
    base-url: ${OPENAI_BASE_URL:}
    api-key: ${OPENAI_API_KEY:}
    model-name: ${OPENAI_MODEL_NAME:gpt-4o-mini}
